/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as GbocRouteImport } from './routes/gboc'
import { Route as BankBuilderRouteImport } from './routes/bank-builder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaunchIndexRouteImport } from './routes/launch.index'
import { Route as GbocIndexRouteImport } from './routes/gboc.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LaunchCategoryRouteImport } from './routes/launch.$category'
import { Route as GbocTransactionsRouteImport } from './routes/gboc.transactions'
import { Route as GbocSettingsRouteImport } from './routes/gboc.settings'
import { Route as GbocReportsRouteImport } from './routes/gboc.reports'
import { Route as GbocOperationsRouteImport } from './routes/gboc.operations'
import { Route as GbocNotificationsRouteImport } from './routes/gboc.notifications'
import { Route as GbocCustomersRouteImport } from './routes/gboc.customers'
import { Route as GbocCommunicationsRouteImport } from './routes/gboc.communications'
import { Route as GbocBanksRouteImport } from './routes/gboc.banks'
import { Route as GbocAuditRouteImport } from './routes/gboc.audit'
import { Route as BanksSlugRouteImport } from './routes/banks.$slug'
import { Route as AdminSectionRouteImport } from './routes/admin.$section'
import { Route as LaunchCategoryIndexRouteImport } from './routes/launch.$category.index'
import { Route as GbocCustomersIndexRouteImport } from './routes/gboc.customers.index'
import { Route as BanksSlugIndexRouteImport } from './routes/banks.$slug.index'
import { Route as ManageBanksIdRouteImport } from './routes/manage.banks.$id'
import { Route as LaunchCategoryCountryRouteImport } from './routes/launch.$category.$country'
import { Route as GbocCustomersIdRouteImport } from './routes/gboc.customers.$id'
import { Route as BanksSlugRegisterRouteImport } from './routes/banks.$slug.register'
import { Route as BanksSlugPortalRouteImport } from './routes/banks.$slug.portal'
import { Route as BanksSlugLoginRouteImport } from './routes/banks.$slug.login'
import { Route as BanksSlugForgotRouteImport } from './routes/banks.$slug.forgot'
import { Route as BanksSlugPageRouteImport } from './routes/banks.$slug.$page'
import { Route as BanksSlugPortalIndexRouteImport } from './routes/banks.$slug.portal.index'
import { Route as BanksSlugPortalTransferRouteImport } from './routes/banks.$slug.portal.transfer'
import { Route as BanksSlugPortalTransactionsRouteImport } from './routes/banks.$slug.portal.transactions'
import { Route as BanksSlugPortalSupportRouteImport } from './routes/banks.$slug.portal.support'
import { Route as BanksSlugPortalStatementsRouteImport } from './routes/banks.$slug.portal.statements'
import { Route as BanksSlugPortalSecurityRouteImport } from './routes/banks.$slug.portal.security'
import { Route as BanksSlugPortalProfileRouteImport } from './routes/banks.$slug.portal.profile'
import { Route as BanksSlugPortalNotificationsRouteImport } from './routes/banks.$slug.portal.notifications'
import { Route as BanksSlugPortalCardsRouteImport } from './routes/banks.$slug.portal.cards'
import { Route as BanksSlugPortalBeneficiariesRouteImport } from './routes/banks.$slug.portal.beneficiaries'
import { Route as BanksSlugPortalAccountsRouteImport } from './routes/banks.$slug.portal.accounts'
import { Route as BanksSlugPortalTransactionsIdRouteImport } from './routes/banks.$slug.portal.transactions.$id'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const GbocRoute = GbocRouteImport.update({
  id: '/gboc',
  path: '/gboc',
  getParentRoute: () => rootRouteImport,
} as any)
const BankBuilderRoute = BankBuilderRouteImport.update({
  id: '/bank-builder',
  path: '/bank-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchIndexRoute = LaunchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LaunchRoute,
} as any)
const GbocIndexRoute = GbocIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GbocRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LaunchCategoryRoute = LaunchCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => LaunchRoute,
} as any)
const GbocTransactionsRoute = GbocTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => GbocRoute,
} as any)
const GbocSettingsRoute = GbocSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => GbocRoute,
} as any)
const GbocReportsRoute = GbocReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => GbocRoute,
} as any)
const GbocOperationsRoute = GbocOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => GbocRoute,
} as any)
const GbocNotificationsRoute = GbocNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => GbocRoute,
} as any)
const GbocCustomersRoute = GbocCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => GbocRoute,
} as any)
const GbocCommunicationsRoute = GbocCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => GbocRoute,
} as any)
const GbocBanksRoute = GbocBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => GbocRoute,
} as any)
const GbocAuditRoute = GbocAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => GbocRoute,
} as any)
const BanksSlugRoute = BanksSlugRouteImport.update({
  id: '/banks/$slug',
  path: '/banks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminRoute,
} as any)
const LaunchCategoryIndexRoute = LaunchCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LaunchCategoryRoute,
} as any)
const GbocCustomersIndexRoute = GbocCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GbocCustomersRoute,
} as any)
const BanksSlugIndexRoute = BanksSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BanksSlugRoute,
} as any)
const ManageBanksIdRoute = ManageBanksIdRouteImport.update({
  id: '/manage/banks/$id',
  path: '/manage/banks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchCategoryCountryRoute = LaunchCategoryCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => LaunchCategoryRoute,
} as any)
const GbocCustomersIdRoute = GbocCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GbocCustomersRoute,
} as any)
const BanksSlugRegisterRoute = BanksSlugRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => BanksSlugRoute,
} as any)
const BanksSlugPortalRoute = BanksSlugPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => BanksSlugRoute,
} as any)
const BanksSlugLoginRoute = BanksSlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BanksSlugRoute,
} as any)
const BanksSlugForgotRoute = BanksSlugForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => BanksSlugRoute,
} as any)
const BanksSlugPageRoute = BanksSlugPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => BanksSlugRoute,
} as any)
const BanksSlugPortalIndexRoute = BanksSlugPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BanksSlugPortalRoute,
} as any)
const BanksSlugPortalTransferRoute = BanksSlugPortalTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => BanksSlugPortalRoute,
} as any)
const BanksSlugPortalTransactionsRoute =
  BanksSlugPortalTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => BanksSlugPortalRoute,
  } as any)
const BanksSlugPortalSupportRoute = BanksSlugPortalSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => BanksSlugPortalRoute,
} as any)
const BanksSlugPortalStatementsRoute =
  BanksSlugPortalStatementsRouteImport.update({
    id: '/statements',
    path: '/statements',
    getParentRoute: () => BanksSlugPortalRoute,
  } as any)
const BanksSlugPortalSecurityRoute = BanksSlugPortalSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => BanksSlugPortalRoute,
} as any)
const BanksSlugPortalProfileRoute = BanksSlugPortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BanksSlugPortalRoute,
} as any)
const BanksSlugPortalNotificationsRoute =
  BanksSlugPortalNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => BanksSlugPortalRoute,
  } as any)
const BanksSlugPortalCardsRoute = BanksSlugPortalCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => BanksSlugPortalRoute,
} as any)
const BanksSlugPortalBeneficiariesRoute =
  BanksSlugPortalBeneficiariesRouteImport.update({
    id: '/beneficiaries',
    path: '/beneficiaries',
    getParentRoute: () => BanksSlugPortalRoute,
  } as any)
const BanksSlugPortalAccountsRoute = BanksSlugPortalAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => BanksSlugPortalRoute,
} as any)
const BanksSlugPortalTransactionsIdRoute =
  BanksSlugPortalTransactionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => BanksSlugPortalTransactionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bank-builder': typeof BankBuilderRoute
  '/gboc': typeof GbocRouteWithChildren
  '/launch': typeof LaunchRouteWithChildren
  '/products': typeof ProductsRoute
  '/admin/$section': typeof AdminSectionRoute
  '/banks/$slug': typeof BanksSlugRouteWithChildren
  '/gboc/audit': typeof GbocAuditRoute
  '/gboc/banks': typeof GbocBanksRoute
  '/gboc/communications': typeof GbocCommunicationsRoute
  '/gboc/customers': typeof GbocCustomersRouteWithChildren
  '/gboc/notifications': typeof GbocNotificationsRoute
  '/gboc/operations': typeof GbocOperationsRoute
  '/gboc/reports': typeof GbocReportsRoute
  '/gboc/settings': typeof GbocSettingsRoute
  '/gboc/transactions': typeof GbocTransactionsRoute
  '/launch/$category': typeof LaunchCategoryRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/gboc/': typeof GbocIndexRoute
  '/launch/': typeof LaunchIndexRoute
  '/banks/$slug/$page': typeof BanksSlugPageRoute
  '/banks/$slug/forgot': typeof BanksSlugForgotRoute
  '/banks/$slug/login': typeof BanksSlugLoginRoute
  '/banks/$slug/portal': typeof BanksSlugPortalRouteWithChildren
  '/banks/$slug/register': typeof BanksSlugRegisterRoute
  '/gboc/customers/$id': typeof GbocCustomersIdRoute
  '/launch/$category/$country': typeof LaunchCategoryCountryRoute
  '/manage/banks/$id': typeof ManageBanksIdRoute
  '/banks/$slug/': typeof BanksSlugIndexRoute
  '/gboc/customers/': typeof GbocCustomersIndexRoute
  '/launch/$category/': typeof LaunchCategoryIndexRoute
  '/banks/$slug/portal/accounts': typeof BanksSlugPortalAccountsRoute
  '/banks/$slug/portal/beneficiaries': typeof BanksSlugPortalBeneficiariesRoute
  '/banks/$slug/portal/cards': typeof BanksSlugPortalCardsRoute
  '/banks/$slug/portal/notifications': typeof BanksSlugPortalNotificationsRoute
  '/banks/$slug/portal/profile': typeof BanksSlugPortalProfileRoute
  '/banks/$slug/portal/security': typeof BanksSlugPortalSecurityRoute
  '/banks/$slug/portal/statements': typeof BanksSlugPortalStatementsRoute
  '/banks/$slug/portal/support': typeof BanksSlugPortalSupportRoute
  '/banks/$slug/portal/transactions': typeof BanksSlugPortalTransactionsRouteWithChildren
  '/banks/$slug/portal/transfer': typeof BanksSlugPortalTransferRoute
  '/banks/$slug/portal/': typeof BanksSlugPortalIndexRoute
  '/banks/$slug/portal/transactions/$id': typeof BanksSlugPortalTransactionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bank-builder': typeof BankBuilderRoute
  '/products': typeof ProductsRoute
  '/admin/$section': typeof AdminSectionRoute
  '/gboc/audit': typeof GbocAuditRoute
  '/gboc/banks': typeof GbocBanksRoute
  '/gboc/communications': typeof GbocCommunicationsRoute
  '/gboc/notifications': typeof GbocNotificationsRoute
  '/gboc/operations': typeof GbocOperationsRoute
  '/gboc/reports': typeof GbocReportsRoute
  '/gboc/settings': typeof GbocSettingsRoute
  '/gboc/transactions': typeof GbocTransactionsRoute
  '/admin': typeof AdminIndexRoute
  '/gboc': typeof GbocIndexRoute
  '/launch': typeof LaunchIndexRoute
  '/banks/$slug/$page': typeof BanksSlugPageRoute
  '/banks/$slug/forgot': typeof BanksSlugForgotRoute
  '/banks/$slug/login': typeof BanksSlugLoginRoute
  '/banks/$slug/register': typeof BanksSlugRegisterRoute
  '/gboc/customers/$id': typeof GbocCustomersIdRoute
  '/launch/$category/$country': typeof LaunchCategoryCountryRoute
  '/manage/banks/$id': typeof ManageBanksIdRoute
  '/banks/$slug': typeof BanksSlugIndexRoute
  '/gboc/customers': typeof GbocCustomersIndexRoute
  '/launch/$category': typeof LaunchCategoryIndexRoute
  '/banks/$slug/portal/accounts': typeof BanksSlugPortalAccountsRoute
  '/banks/$slug/portal/beneficiaries': typeof BanksSlugPortalBeneficiariesRoute
  '/banks/$slug/portal/cards': typeof BanksSlugPortalCardsRoute
  '/banks/$slug/portal/notifications': typeof BanksSlugPortalNotificationsRoute
  '/banks/$slug/portal/profile': typeof BanksSlugPortalProfileRoute
  '/banks/$slug/portal/security': typeof BanksSlugPortalSecurityRoute
  '/banks/$slug/portal/statements': typeof BanksSlugPortalStatementsRoute
  '/banks/$slug/portal/support': typeof BanksSlugPortalSupportRoute
  '/banks/$slug/portal/transactions': typeof BanksSlugPortalTransactionsRouteWithChildren
  '/banks/$slug/portal/transfer': typeof BanksSlugPortalTransferRoute
  '/banks/$slug/portal': typeof BanksSlugPortalIndexRoute
  '/banks/$slug/portal/transactions/$id': typeof BanksSlugPortalTransactionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bank-builder': typeof BankBuilderRoute
  '/gboc': typeof GbocRouteWithChildren
  '/launch': typeof LaunchRouteWithChildren
  '/products': typeof ProductsRoute
  '/admin/$section': typeof AdminSectionRoute
  '/banks/$slug': typeof BanksSlugRouteWithChildren
  '/gboc/audit': typeof GbocAuditRoute
  '/gboc/banks': typeof GbocBanksRoute
  '/gboc/communications': typeof GbocCommunicationsRoute
  '/gboc/customers': typeof GbocCustomersRouteWithChildren
  '/gboc/notifications': typeof GbocNotificationsRoute
  '/gboc/operations': typeof GbocOperationsRoute
  '/gboc/reports': typeof GbocReportsRoute
  '/gboc/settings': typeof GbocSettingsRoute
  '/gboc/transactions': typeof GbocTransactionsRoute
  '/launch/$category': typeof LaunchCategoryRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/gboc/': typeof GbocIndexRoute
  '/launch/': typeof LaunchIndexRoute
  '/banks/$slug/$page': typeof BanksSlugPageRoute
  '/banks/$slug/forgot': typeof BanksSlugForgotRoute
  '/banks/$slug/login': typeof BanksSlugLoginRoute
  '/banks/$slug/portal': typeof BanksSlugPortalRouteWithChildren
  '/banks/$slug/register': typeof BanksSlugRegisterRoute
  '/gboc/customers/$id': typeof GbocCustomersIdRoute
  '/launch/$category/$country': typeof LaunchCategoryCountryRoute
  '/manage/banks/$id': typeof ManageBanksIdRoute
  '/banks/$slug/': typeof BanksSlugIndexRoute
  '/gboc/customers/': typeof GbocCustomersIndexRoute
  '/launch/$category/': typeof LaunchCategoryIndexRoute
  '/banks/$slug/portal/accounts': typeof BanksSlugPortalAccountsRoute
  '/banks/$slug/portal/beneficiaries': typeof BanksSlugPortalBeneficiariesRoute
  '/banks/$slug/portal/cards': typeof BanksSlugPortalCardsRoute
  '/banks/$slug/portal/notifications': typeof BanksSlugPortalNotificationsRoute
  '/banks/$slug/portal/profile': typeof BanksSlugPortalProfileRoute
  '/banks/$slug/portal/security': typeof BanksSlugPortalSecurityRoute
  '/banks/$slug/portal/statements': typeof BanksSlugPortalStatementsRoute
  '/banks/$slug/portal/support': typeof BanksSlugPortalSupportRoute
  '/banks/$slug/portal/transactions': typeof BanksSlugPortalTransactionsRouteWithChildren
  '/banks/$slug/portal/transfer': typeof BanksSlugPortalTransferRoute
  '/banks/$slug/portal/': typeof BanksSlugPortalIndexRoute
  '/banks/$slug/portal/transactions/$id': typeof BanksSlugPortalTransactionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bank-builder'
    | '/gboc'
    | '/launch'
    | '/products'
    | '/admin/$section'
    | '/banks/$slug'
    | '/gboc/audit'
    | '/gboc/banks'
    | '/gboc/communications'
    | '/gboc/customers'
    | '/gboc/notifications'
    | '/gboc/operations'
    | '/gboc/reports'
    | '/gboc/settings'
    | '/gboc/transactions'
    | '/launch/$category'
    | '/admin/'
    | '/gboc/'
    | '/launch/'
    | '/banks/$slug/$page'
    | '/banks/$slug/forgot'
    | '/banks/$slug/login'
    | '/banks/$slug/portal'
    | '/banks/$slug/register'
    | '/gboc/customers/$id'
    | '/launch/$category/$country'
    | '/manage/banks/$id'
    | '/banks/$slug/'
    | '/gboc/customers/'
    | '/launch/$category/'
    | '/banks/$slug/portal/accounts'
    | '/banks/$slug/portal/beneficiaries'
    | '/banks/$slug/portal/cards'
    | '/banks/$slug/portal/notifications'
    | '/banks/$slug/portal/profile'
    | '/banks/$slug/portal/security'
    | '/banks/$slug/portal/statements'
    | '/banks/$slug/portal/support'
    | '/banks/$slug/portal/transactions'
    | '/banks/$slug/portal/transfer'
    | '/banks/$slug/portal/'
    | '/banks/$slug/portal/transactions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bank-builder'
    | '/products'
    | '/admin/$section'
    | '/gboc/audit'
    | '/gboc/banks'
    | '/gboc/communications'
    | '/gboc/notifications'
    | '/gboc/operations'
    | '/gboc/reports'
    | '/gboc/settings'
    | '/gboc/transactions'
    | '/admin'
    | '/gboc'
    | '/launch'
    | '/banks/$slug/$page'
    | '/banks/$slug/forgot'
    | '/banks/$slug/login'
    | '/banks/$slug/register'
    | '/gboc/customers/$id'
    | '/launch/$category/$country'
    | '/manage/banks/$id'
    | '/banks/$slug'
    | '/gboc/customers'
    | '/launch/$category'
    | '/banks/$slug/portal/accounts'
    | '/banks/$slug/portal/beneficiaries'
    | '/banks/$slug/portal/cards'
    | '/banks/$slug/portal/notifications'
    | '/banks/$slug/portal/profile'
    | '/banks/$slug/portal/security'
    | '/banks/$slug/portal/statements'
    | '/banks/$slug/portal/support'
    | '/banks/$slug/portal/transactions'
    | '/banks/$slug/portal/transfer'
    | '/banks/$slug/portal'
    | '/banks/$slug/portal/transactions/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/bank-builder'
    | '/gboc'
    | '/launch'
    | '/products'
    | '/admin/$section'
    | '/banks/$slug'
    | '/gboc/audit'
    | '/gboc/banks'
    | '/gboc/communications'
    | '/gboc/customers'
    | '/gboc/notifications'
    | '/gboc/operations'
    | '/gboc/reports'
    | '/gboc/settings'
    | '/gboc/transactions'
    | '/launch/$category'
    | '/admin/'
    | '/gboc/'
    | '/launch/'
    | '/banks/$slug/$page'
    | '/banks/$slug/forgot'
    | '/banks/$slug/login'
    | '/banks/$slug/portal'
    | '/banks/$slug/register'
    | '/gboc/customers/$id'
    | '/launch/$category/$country'
    | '/manage/banks/$id'
    | '/banks/$slug/'
    | '/gboc/customers/'
    | '/launch/$category/'
    | '/banks/$slug/portal/accounts'
    | '/banks/$slug/portal/beneficiaries'
    | '/banks/$slug/portal/cards'
    | '/banks/$slug/portal/notifications'
    | '/banks/$slug/portal/profile'
    | '/banks/$slug/portal/security'
    | '/banks/$slug/portal/statements'
    | '/banks/$slug/portal/support'
    | '/banks/$slug/portal/transactions'
    | '/banks/$slug/portal/transfer'
    | '/banks/$slug/portal/'
    | '/banks/$slug/portal/transactions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BankBuilderRoute: typeof BankBuilderRoute
  GbocRoute: typeof GbocRouteWithChildren
  LaunchRoute: typeof LaunchRouteWithChildren
  ProductsRoute: typeof ProductsRoute
  BanksSlugRoute: typeof BanksSlugRouteWithChildren
  ManageBanksIdRoute: typeof ManageBanksIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gboc': {
      id: '/gboc'
      path: '/gboc'
      fullPath: '/gboc'
      preLoaderRoute: typeof GbocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-builder': {
      id: '/bank-builder'
      path: '/bank-builder'
      fullPath: '/bank-builder'
      preLoaderRoute: typeof BankBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/': {
      id: '/launch/'
      path: '/'
      fullPath: '/launch/'
      preLoaderRoute: typeof LaunchIndexRouteImport
      parentRoute: typeof LaunchRoute
    }
    '/gboc/': {
      id: '/gboc/'
      path: '/'
      fullPath: '/gboc/'
      preLoaderRoute: typeof GbocIndexRouteImport
      parentRoute: typeof GbocRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/launch/$category': {
      id: '/launch/$category'
      path: '/$category'
      fullPath: '/launch/$category'
      preLoaderRoute: typeof LaunchCategoryRouteImport
      parentRoute: typeof LaunchRoute
    }
    '/gboc/transactions': {
      id: '/gboc/transactions'
      path: '/transactions'
      fullPath: '/gboc/transactions'
      preLoaderRoute: typeof GbocTransactionsRouteImport
      parentRoute: typeof GbocRoute
    }
    '/gboc/settings': {
      id: '/gboc/settings'
      path: '/settings'
      fullPath: '/gboc/settings'
      preLoaderRoute: typeof GbocSettingsRouteImport
      parentRoute: typeof GbocRoute
    }
    '/gboc/reports': {
      id: '/gboc/reports'
      path: '/reports'
      fullPath: '/gboc/reports'
      preLoaderRoute: typeof GbocReportsRouteImport
      parentRoute: typeof GbocRoute
    }
    '/gboc/operations': {
      id: '/gboc/operations'
      path: '/operations'
      fullPath: '/gboc/operations'
      preLoaderRoute: typeof GbocOperationsRouteImport
      parentRoute: typeof GbocRoute
    }
    '/gboc/notifications': {
      id: '/gboc/notifications'
      path: '/notifications'
      fullPath: '/gboc/notifications'
      preLoaderRoute: typeof GbocNotificationsRouteImport
      parentRoute: typeof GbocRoute
    }
    '/gboc/customers': {
      id: '/gboc/customers'
      path: '/customers'
      fullPath: '/gboc/customers'
      preLoaderRoute: typeof GbocCustomersRouteImport
      parentRoute: typeof GbocRoute
    }
    '/gboc/communications': {
      id: '/gboc/communications'
      path: '/communications'
      fullPath: '/gboc/communications'
      preLoaderRoute: typeof GbocCommunicationsRouteImport
      parentRoute: typeof GbocRoute
    }
    '/gboc/banks': {
      id: '/gboc/banks'
      path: '/banks'
      fullPath: '/gboc/banks'
      preLoaderRoute: typeof GbocBanksRouteImport
      parentRoute: typeof GbocRoute
    }
    '/gboc/audit': {
      id: '/gboc/audit'
      path: '/audit'
      fullPath: '/gboc/audit'
      preLoaderRoute: typeof GbocAuditRouteImport
      parentRoute: typeof GbocRoute
    }
    '/banks/$slug': {
      id: '/banks/$slug'
      path: '/banks/$slug'
      fullPath: '/banks/$slug'
      preLoaderRoute: typeof BanksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/launch/$category/': {
      id: '/launch/$category/'
      path: '/'
      fullPath: '/launch/$category/'
      preLoaderRoute: typeof LaunchCategoryIndexRouteImport
      parentRoute: typeof LaunchCategoryRoute
    }
    '/gboc/customers/': {
      id: '/gboc/customers/'
      path: '/'
      fullPath: '/gboc/customers/'
      preLoaderRoute: typeof GbocCustomersIndexRouteImport
      parentRoute: typeof GbocCustomersRoute
    }
    '/banks/$slug/': {
      id: '/banks/$slug/'
      path: '/'
      fullPath: '/banks/$slug/'
      preLoaderRoute: typeof BanksSlugIndexRouteImport
      parentRoute: typeof BanksSlugRoute
    }
    '/manage/banks/$id': {
      id: '/manage/banks/$id'
      path: '/manage/banks/$id'
      fullPath: '/manage/banks/$id'
      preLoaderRoute: typeof ManageBanksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/$category/$country': {
      id: '/launch/$category/$country'
      path: '/$country'
      fullPath: '/launch/$category/$country'
      preLoaderRoute: typeof LaunchCategoryCountryRouteImport
      parentRoute: typeof LaunchCategoryRoute
    }
    '/gboc/customers/$id': {
      id: '/gboc/customers/$id'
      path: '/$id'
      fullPath: '/gboc/customers/$id'
      preLoaderRoute: typeof GbocCustomersIdRouteImport
      parentRoute: typeof GbocCustomersRoute
    }
    '/banks/$slug/register': {
      id: '/banks/$slug/register'
      path: '/register'
      fullPath: '/banks/$slug/register'
      preLoaderRoute: typeof BanksSlugRegisterRouteImport
      parentRoute: typeof BanksSlugRoute
    }
    '/banks/$slug/portal': {
      id: '/banks/$slug/portal'
      path: '/portal'
      fullPath: '/banks/$slug/portal'
      preLoaderRoute: typeof BanksSlugPortalRouteImport
      parentRoute: typeof BanksSlugRoute
    }
    '/banks/$slug/login': {
      id: '/banks/$slug/login'
      path: '/login'
      fullPath: '/banks/$slug/login'
      preLoaderRoute: typeof BanksSlugLoginRouteImport
      parentRoute: typeof BanksSlugRoute
    }
    '/banks/$slug/forgot': {
      id: '/banks/$slug/forgot'
      path: '/forgot'
      fullPath: '/banks/$slug/forgot'
      preLoaderRoute: typeof BanksSlugForgotRouteImport
      parentRoute: typeof BanksSlugRoute
    }
    '/banks/$slug/$page': {
      id: '/banks/$slug/$page'
      path: '/$page'
      fullPath: '/banks/$slug/$page'
      preLoaderRoute: typeof BanksSlugPageRouteImport
      parentRoute: typeof BanksSlugRoute
    }
    '/banks/$slug/portal/': {
      id: '/banks/$slug/portal/'
      path: '/'
      fullPath: '/banks/$slug/portal/'
      preLoaderRoute: typeof BanksSlugPortalIndexRouteImport
      parentRoute: typeof BanksSlugPortalRoute
    }
    '/banks/$slug/portal/transfer': {
      id: '/banks/$slug/portal/transfer'
      path: '/transfer'
      fullPath: '/banks/$slug/portal/transfer'
      preLoaderRoute: typeof BanksSlugPortalTransferRouteImport
      parentRoute: typeof BanksSlugPortalRoute
    }
    '/banks/$slug/portal/transactions': {
      id: '/banks/$slug/portal/transactions'
      path: '/transactions'
      fullPath: '/banks/$slug/portal/transactions'
      preLoaderRoute: typeof BanksSlugPortalTransactionsRouteImport
      parentRoute: typeof BanksSlugPortalRoute
    }
    '/banks/$slug/portal/support': {
      id: '/banks/$slug/portal/support'
      path: '/support'
      fullPath: '/banks/$slug/portal/support'
      preLoaderRoute: typeof BanksSlugPortalSupportRouteImport
      parentRoute: typeof BanksSlugPortalRoute
    }
    '/banks/$slug/portal/statements': {
      id: '/banks/$slug/portal/statements'
      path: '/statements'
      fullPath: '/banks/$slug/portal/statements'
      preLoaderRoute: typeof BanksSlugPortalStatementsRouteImport
      parentRoute: typeof BanksSlugPortalRoute
    }
    '/banks/$slug/portal/security': {
      id: '/banks/$slug/portal/security'
      path: '/security'
      fullPath: '/banks/$slug/portal/security'
      preLoaderRoute: typeof BanksSlugPortalSecurityRouteImport
      parentRoute: typeof BanksSlugPortalRoute
    }
    '/banks/$slug/portal/profile': {
      id: '/banks/$slug/portal/profile'
      path: '/profile'
      fullPath: '/banks/$slug/portal/profile'
      preLoaderRoute: typeof BanksSlugPortalProfileRouteImport
      parentRoute: typeof BanksSlugPortalRoute
    }
    '/banks/$slug/portal/notifications': {
      id: '/banks/$slug/portal/notifications'
      path: '/notifications'
      fullPath: '/banks/$slug/portal/notifications'
      preLoaderRoute: typeof BanksSlugPortalNotificationsRouteImport
      parentRoute: typeof BanksSlugPortalRoute
    }
    '/banks/$slug/portal/cards': {
      id: '/banks/$slug/portal/cards'
      path: '/cards'
      fullPath: '/banks/$slug/portal/cards'
      preLoaderRoute: typeof BanksSlugPortalCardsRouteImport
      parentRoute: typeof BanksSlugPortalRoute
    }
    '/banks/$slug/portal/beneficiaries': {
      id: '/banks/$slug/portal/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/banks/$slug/portal/beneficiaries'
      preLoaderRoute: typeof BanksSlugPortalBeneficiariesRouteImport
      parentRoute: typeof BanksSlugPortalRoute
    }
    '/banks/$slug/portal/accounts': {
      id: '/banks/$slug/portal/accounts'
      path: '/accounts'
      fullPath: '/banks/$slug/portal/accounts'
      preLoaderRoute: typeof BanksSlugPortalAccountsRouteImport
      parentRoute: typeof BanksSlugPortalRoute
    }
    '/banks/$slug/portal/transactions/$id': {
      id: '/banks/$slug/portal/transactions/$id'
      path: '/$id'
      fullPath: '/banks/$slug/portal/transactions/$id'
      preLoaderRoute: typeof BanksSlugPortalTransactionsIdRouteImport
      parentRoute: typeof BanksSlugPortalTransactionsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSectionRoute: typeof AdminSectionRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSectionRoute: AdminSectionRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GbocCustomersRouteChildren {
  GbocCustomersIdRoute: typeof GbocCustomersIdRoute
  GbocCustomersIndexRoute: typeof GbocCustomersIndexRoute
}

const GbocCustomersRouteChildren: GbocCustomersRouteChildren = {
  GbocCustomersIdRoute: GbocCustomersIdRoute,
  GbocCustomersIndexRoute: GbocCustomersIndexRoute,
}

const GbocCustomersRouteWithChildren = GbocCustomersRoute._addFileChildren(
  GbocCustomersRouteChildren,
)

interface GbocRouteChildren {
  GbocAuditRoute: typeof GbocAuditRoute
  GbocBanksRoute: typeof GbocBanksRoute
  GbocCommunicationsRoute: typeof GbocCommunicationsRoute
  GbocCustomersRoute: typeof GbocCustomersRouteWithChildren
  GbocNotificationsRoute: typeof GbocNotificationsRoute
  GbocOperationsRoute: typeof GbocOperationsRoute
  GbocReportsRoute: typeof GbocReportsRoute
  GbocSettingsRoute: typeof GbocSettingsRoute
  GbocTransactionsRoute: typeof GbocTransactionsRoute
  GbocIndexRoute: typeof GbocIndexRoute
}

const GbocRouteChildren: GbocRouteChildren = {
  GbocAuditRoute: GbocAuditRoute,
  GbocBanksRoute: GbocBanksRoute,
  GbocCommunicationsRoute: GbocCommunicationsRoute,
  GbocCustomersRoute: GbocCustomersRouteWithChildren,
  GbocNotificationsRoute: GbocNotificationsRoute,
  GbocOperationsRoute: GbocOperationsRoute,
  GbocReportsRoute: GbocReportsRoute,
  GbocSettingsRoute: GbocSettingsRoute,
  GbocTransactionsRoute: GbocTransactionsRoute,
  GbocIndexRoute: GbocIndexRoute,
}

const GbocRouteWithChildren = GbocRoute._addFileChildren(GbocRouteChildren)

interface LaunchCategoryRouteChildren {
  LaunchCategoryCountryRoute: typeof LaunchCategoryCountryRoute
  LaunchCategoryIndexRoute: typeof LaunchCategoryIndexRoute
}

const LaunchCategoryRouteChildren: LaunchCategoryRouteChildren = {
  LaunchCategoryCountryRoute: LaunchCategoryCountryRoute,
  LaunchCategoryIndexRoute: LaunchCategoryIndexRoute,
}

const LaunchCategoryRouteWithChildren = LaunchCategoryRoute._addFileChildren(
  LaunchCategoryRouteChildren,
)

interface LaunchRouteChildren {
  LaunchCategoryRoute: typeof LaunchCategoryRouteWithChildren
  LaunchIndexRoute: typeof LaunchIndexRoute
}

const LaunchRouteChildren: LaunchRouteChildren = {
  LaunchCategoryRoute: LaunchCategoryRouteWithChildren,
  LaunchIndexRoute: LaunchIndexRoute,
}

const LaunchRouteWithChildren =
  LaunchRoute._addFileChildren(LaunchRouteChildren)

interface BanksSlugPortalTransactionsRouteChildren {
  BanksSlugPortalTransactionsIdRoute: typeof BanksSlugPortalTransactionsIdRoute
}

const BanksSlugPortalTransactionsRouteChildren: BanksSlugPortalTransactionsRouteChildren =
  {
    BanksSlugPortalTransactionsIdRoute: BanksSlugPortalTransactionsIdRoute,
  }

const BanksSlugPortalTransactionsRouteWithChildren =
  BanksSlugPortalTransactionsRoute._addFileChildren(
    BanksSlugPortalTransactionsRouteChildren,
  )

interface BanksSlugPortalRouteChildren {
  BanksSlugPortalAccountsRoute: typeof BanksSlugPortalAccountsRoute
  BanksSlugPortalBeneficiariesRoute: typeof BanksSlugPortalBeneficiariesRoute
  BanksSlugPortalCardsRoute: typeof BanksSlugPortalCardsRoute
  BanksSlugPortalNotificationsRoute: typeof BanksSlugPortalNotificationsRoute
  BanksSlugPortalProfileRoute: typeof BanksSlugPortalProfileRoute
  BanksSlugPortalSecurityRoute: typeof BanksSlugPortalSecurityRoute
  BanksSlugPortalStatementsRoute: typeof BanksSlugPortalStatementsRoute
  BanksSlugPortalSupportRoute: typeof BanksSlugPortalSupportRoute
  BanksSlugPortalTransactionsRoute: typeof BanksSlugPortalTransactionsRouteWithChildren
  BanksSlugPortalTransferRoute: typeof BanksSlugPortalTransferRoute
  BanksSlugPortalIndexRoute: typeof BanksSlugPortalIndexRoute
}

const BanksSlugPortalRouteChildren: BanksSlugPortalRouteChildren = {
  BanksSlugPortalAccountsRoute: BanksSlugPortalAccountsRoute,
  BanksSlugPortalBeneficiariesRoute: BanksSlugPortalBeneficiariesRoute,
  BanksSlugPortalCardsRoute: BanksSlugPortalCardsRoute,
  BanksSlugPortalNotificationsRoute: BanksSlugPortalNotificationsRoute,
  BanksSlugPortalProfileRoute: BanksSlugPortalProfileRoute,
  BanksSlugPortalSecurityRoute: BanksSlugPortalSecurityRoute,
  BanksSlugPortalStatementsRoute: BanksSlugPortalStatementsRoute,
  BanksSlugPortalSupportRoute: BanksSlugPortalSupportRoute,
  BanksSlugPortalTransactionsRoute:
    BanksSlugPortalTransactionsRouteWithChildren,
  BanksSlugPortalTransferRoute: BanksSlugPortalTransferRoute,
  BanksSlugPortalIndexRoute: BanksSlugPortalIndexRoute,
}

const BanksSlugPortalRouteWithChildren = BanksSlugPortalRoute._addFileChildren(
  BanksSlugPortalRouteChildren,
)

interface BanksSlugRouteChildren {
  BanksSlugPageRoute: typeof BanksSlugPageRoute
  BanksSlugForgotRoute: typeof BanksSlugForgotRoute
  BanksSlugLoginRoute: typeof BanksSlugLoginRoute
  BanksSlugPortalRoute: typeof BanksSlugPortalRouteWithChildren
  BanksSlugRegisterRoute: typeof BanksSlugRegisterRoute
  BanksSlugIndexRoute: typeof BanksSlugIndexRoute
}

const BanksSlugRouteChildren: BanksSlugRouteChildren = {
  BanksSlugPageRoute: BanksSlugPageRoute,
  BanksSlugForgotRoute: BanksSlugForgotRoute,
  BanksSlugLoginRoute: BanksSlugLoginRoute,
  BanksSlugPortalRoute: BanksSlugPortalRouteWithChildren,
  BanksSlugRegisterRoute: BanksSlugRegisterRoute,
  BanksSlugIndexRoute: BanksSlugIndexRoute,
}

const BanksSlugRouteWithChildren = BanksSlugRoute._addFileChildren(
  BanksSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BankBuilderRoute: BankBuilderRoute,
  GbocRoute: GbocRouteWithChildren,
  LaunchRoute: LaunchRouteWithChildren,
  ProductsRoute: ProductsRoute,
  BanksSlugRoute: BanksSlugRouteWithChildren,
  ManageBanksIdRoute: ManageBanksIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
