/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as BankBuilderRouteImport } from './routes/bank-builder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaunchIndexRouteImport } from './routes/launch.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LaunchCategoryRouteImport } from './routes/launch.$category'
import { Route as BanksSlugRouteImport } from './routes/banks.$slug'
import { Route as AdminSectionRouteImport } from './routes/admin.$section'
import { Route as LaunchCategoryIndexRouteImport } from './routes/launch.$category.index'
import { Route as ManageBanksIdRouteImport } from './routes/manage.banks.$id'
import { Route as LaunchCategoryCountryRouteImport } from './routes/launch.$category.$country'
import { Route as BanksSlugRegisterRouteImport } from './routes/banks.$slug.register'
import { Route as BanksSlugPortalRouteImport } from './routes/banks.$slug.portal'
import { Route as BanksSlugLoginRouteImport } from './routes/banks.$slug.login'
import { Route as BanksSlugForgotRouteImport } from './routes/banks.$slug.forgot'
import { Route as BanksSlugPageRouteImport } from './routes/banks.$slug.$page'
import { Route as BanksSlugPortalIndexRouteImport } from './routes/banks.$slug.portal.index'
import { Route as BanksSlugPortalProfileRouteImport } from './routes/banks.$slug.portal.profile'
import { Route as BanksSlugPortalAccountsRouteImport } from './routes/banks.$slug.portal.accounts'

const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const BankBuilderRoute = BankBuilderRouteImport.update({
  id: '/bank-builder',
  path: '/bank-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchIndexRoute = LaunchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LaunchRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LaunchCategoryRoute = LaunchCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => LaunchRoute,
} as any)
const BanksSlugRoute = BanksSlugRouteImport.update({
  id: '/banks/$slug',
  path: '/banks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminRoute,
} as any)
const LaunchCategoryIndexRoute = LaunchCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LaunchCategoryRoute,
} as any)
const ManageBanksIdRoute = ManageBanksIdRouteImport.update({
  id: '/manage/banks/$id',
  path: '/manage/banks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchCategoryCountryRoute = LaunchCategoryCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => LaunchCategoryRoute,
} as any)
const BanksSlugRegisterRoute = BanksSlugRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => BanksSlugRoute,
} as any)
const BanksSlugPortalRoute = BanksSlugPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => BanksSlugRoute,
} as any)
const BanksSlugLoginRoute = BanksSlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BanksSlugRoute,
} as any)
const BanksSlugForgotRoute = BanksSlugForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => BanksSlugRoute,
} as any)
const BanksSlugPageRoute = BanksSlugPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => BanksSlugRoute,
} as any)
const BanksSlugPortalIndexRoute = BanksSlugPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BanksSlugPortalRoute,
} as any)
const BanksSlugPortalProfileRoute = BanksSlugPortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BanksSlugPortalRoute,
} as any)
const BanksSlugPortalAccountsRoute = BanksSlugPortalAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => BanksSlugPortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bank-builder': typeof BankBuilderRoute
  '/launch': typeof LaunchRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/banks/$slug': typeof BanksSlugRouteWithChildren
  '/launch/$category': typeof LaunchCategoryRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/launch/': typeof LaunchIndexRoute
  '/banks/$slug/$page': typeof BanksSlugPageRoute
  '/banks/$slug/forgot': typeof BanksSlugForgotRoute
  '/banks/$slug/login': typeof BanksSlugLoginRoute
  '/banks/$slug/portal': typeof BanksSlugPortalRouteWithChildren
  '/banks/$slug/register': typeof BanksSlugRegisterRoute
  '/launch/$category/$country': typeof LaunchCategoryCountryRoute
  '/manage/banks/$id': typeof ManageBanksIdRoute
  '/launch/$category/': typeof LaunchCategoryIndexRoute
  '/banks/$slug/portal/accounts': typeof BanksSlugPortalAccountsRoute
  '/banks/$slug/portal/profile': typeof BanksSlugPortalProfileRoute
  '/banks/$slug/portal/': typeof BanksSlugPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bank-builder': typeof BankBuilderRoute
  '/admin/$section': typeof AdminSectionRoute
  '/banks/$slug': typeof BanksSlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/launch': typeof LaunchIndexRoute
  '/banks/$slug/$page': typeof BanksSlugPageRoute
  '/banks/$slug/forgot': typeof BanksSlugForgotRoute
  '/banks/$slug/login': typeof BanksSlugLoginRoute
  '/banks/$slug/register': typeof BanksSlugRegisterRoute
  '/launch/$category/$country': typeof LaunchCategoryCountryRoute
  '/manage/banks/$id': typeof ManageBanksIdRoute
  '/launch/$category': typeof LaunchCategoryIndexRoute
  '/banks/$slug/portal/accounts': typeof BanksSlugPortalAccountsRoute
  '/banks/$slug/portal/profile': typeof BanksSlugPortalProfileRoute
  '/banks/$slug/portal': typeof BanksSlugPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bank-builder': typeof BankBuilderRoute
  '/launch': typeof LaunchRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/banks/$slug': typeof BanksSlugRouteWithChildren
  '/launch/$category': typeof LaunchCategoryRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/launch/': typeof LaunchIndexRoute
  '/banks/$slug/$page': typeof BanksSlugPageRoute
  '/banks/$slug/forgot': typeof BanksSlugForgotRoute
  '/banks/$slug/login': typeof BanksSlugLoginRoute
  '/banks/$slug/portal': typeof BanksSlugPortalRouteWithChildren
  '/banks/$slug/register': typeof BanksSlugRegisterRoute
  '/launch/$category/$country': typeof LaunchCategoryCountryRoute
  '/manage/banks/$id': typeof ManageBanksIdRoute
  '/launch/$category/': typeof LaunchCategoryIndexRoute
  '/banks/$slug/portal/accounts': typeof BanksSlugPortalAccountsRoute
  '/banks/$slug/portal/profile': typeof BanksSlugPortalProfileRoute
  '/banks/$slug/portal/': typeof BanksSlugPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bank-builder'
    | '/launch'
    | '/admin/$section'
    | '/banks/$slug'
    | '/launch/$category'
    | '/admin/'
    | '/launch/'
    | '/banks/$slug/$page'
    | '/banks/$slug/forgot'
    | '/banks/$slug/login'
    | '/banks/$slug/portal'
    | '/banks/$slug/register'
    | '/launch/$category/$country'
    | '/manage/banks/$id'
    | '/launch/$category/'
    | '/banks/$slug/portal/accounts'
    | '/banks/$slug/portal/profile'
    | '/banks/$slug/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bank-builder'
    | '/admin/$section'
    | '/banks/$slug'
    | '/admin'
    | '/launch'
    | '/banks/$slug/$page'
    | '/banks/$slug/forgot'
    | '/banks/$slug/login'
    | '/banks/$slug/register'
    | '/launch/$category/$country'
    | '/manage/banks/$id'
    | '/launch/$category'
    | '/banks/$slug/portal/accounts'
    | '/banks/$slug/portal/profile'
    | '/banks/$slug/portal'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/bank-builder'
    | '/launch'
    | '/admin/$section'
    | '/banks/$slug'
    | '/launch/$category'
    | '/admin/'
    | '/launch/'
    | '/banks/$slug/$page'
    | '/banks/$slug/forgot'
    | '/banks/$slug/login'
    | '/banks/$slug/portal'
    | '/banks/$slug/register'
    | '/launch/$category/$country'
    | '/manage/banks/$id'
    | '/launch/$category/'
    | '/banks/$slug/portal/accounts'
    | '/banks/$slug/portal/profile'
    | '/banks/$slug/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BankBuilderRoute: typeof BankBuilderRoute
  LaunchRoute: typeof LaunchRouteWithChildren
  BanksSlugRoute: typeof BanksSlugRouteWithChildren
  ManageBanksIdRoute: typeof ManageBanksIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-builder': {
      id: '/bank-builder'
      path: '/bank-builder'
      fullPath: '/bank-builder'
      preLoaderRoute: typeof BankBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/': {
      id: '/launch/'
      path: '/'
      fullPath: '/launch/'
      preLoaderRoute: typeof LaunchIndexRouteImport
      parentRoute: typeof LaunchRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/launch/$category': {
      id: '/launch/$category'
      path: '/$category'
      fullPath: '/launch/$category'
      preLoaderRoute: typeof LaunchCategoryRouteImport
      parentRoute: typeof LaunchRoute
    }
    '/banks/$slug': {
      id: '/banks/$slug'
      path: '/banks/$slug'
      fullPath: '/banks/$slug'
      preLoaderRoute: typeof BanksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/launch/$category/': {
      id: '/launch/$category/'
      path: '/'
      fullPath: '/launch/$category/'
      preLoaderRoute: typeof LaunchCategoryIndexRouteImport
      parentRoute: typeof LaunchCategoryRoute
    }
    '/manage/banks/$id': {
      id: '/manage/banks/$id'
      path: '/manage/banks/$id'
      fullPath: '/manage/banks/$id'
      preLoaderRoute: typeof ManageBanksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/$category/$country': {
      id: '/launch/$category/$country'
      path: '/$country'
      fullPath: '/launch/$category/$country'
      preLoaderRoute: typeof LaunchCategoryCountryRouteImport
      parentRoute: typeof LaunchCategoryRoute
    }
    '/banks/$slug/register': {
      id: '/banks/$slug/register'
      path: '/register'
      fullPath: '/banks/$slug/register'
      preLoaderRoute: typeof BanksSlugRegisterRouteImport
      parentRoute: typeof BanksSlugRoute
    }
    '/banks/$slug/portal': {
      id: '/banks/$slug/portal'
      path: '/portal'
      fullPath: '/banks/$slug/portal'
      preLoaderRoute: typeof BanksSlugPortalRouteImport
      parentRoute: typeof BanksSlugRoute
    }
    '/banks/$slug/login': {
      id: '/banks/$slug/login'
      path: '/login'
      fullPath: '/banks/$slug/login'
      preLoaderRoute: typeof BanksSlugLoginRouteImport
      parentRoute: typeof BanksSlugRoute
    }
    '/banks/$slug/forgot': {
      id: '/banks/$slug/forgot'
      path: '/forgot'
      fullPath: '/banks/$slug/forgot'
      preLoaderRoute: typeof BanksSlugForgotRouteImport
      parentRoute: typeof BanksSlugRoute
    }
    '/banks/$slug/$page': {
      id: '/banks/$slug/$page'
      path: '/$page'
      fullPath: '/banks/$slug/$page'
      preLoaderRoute: typeof BanksSlugPageRouteImport
      parentRoute: typeof BanksSlugRoute
    }
    '/banks/$slug/portal/': {
      id: '/banks/$slug/portal/'
      path: '/'
      fullPath: '/banks/$slug/portal/'
      preLoaderRoute: typeof BanksSlugPortalIndexRouteImport
      parentRoute: typeof BanksSlugPortalRoute
    }
    '/banks/$slug/portal/profile': {
      id: '/banks/$slug/portal/profile'
      path: '/profile'
      fullPath: '/banks/$slug/portal/profile'
      preLoaderRoute: typeof BanksSlugPortalProfileRouteImport
      parentRoute: typeof BanksSlugPortalRoute
    }
    '/banks/$slug/portal/accounts': {
      id: '/banks/$slug/portal/accounts'
      path: '/accounts'
      fullPath: '/banks/$slug/portal/accounts'
      preLoaderRoute: typeof BanksSlugPortalAccountsRouteImport
      parentRoute: typeof BanksSlugPortalRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSectionRoute: typeof AdminSectionRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSectionRoute: AdminSectionRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LaunchCategoryRouteChildren {
  LaunchCategoryCountryRoute: typeof LaunchCategoryCountryRoute
  LaunchCategoryIndexRoute: typeof LaunchCategoryIndexRoute
}

const LaunchCategoryRouteChildren: LaunchCategoryRouteChildren = {
  LaunchCategoryCountryRoute: LaunchCategoryCountryRoute,
  LaunchCategoryIndexRoute: LaunchCategoryIndexRoute,
}

const LaunchCategoryRouteWithChildren = LaunchCategoryRoute._addFileChildren(
  LaunchCategoryRouteChildren,
)

interface LaunchRouteChildren {
  LaunchCategoryRoute: typeof LaunchCategoryRouteWithChildren
  LaunchIndexRoute: typeof LaunchIndexRoute
}

const LaunchRouteChildren: LaunchRouteChildren = {
  LaunchCategoryRoute: LaunchCategoryRouteWithChildren,
  LaunchIndexRoute: LaunchIndexRoute,
}

const LaunchRouteWithChildren =
  LaunchRoute._addFileChildren(LaunchRouteChildren)

interface BanksSlugPortalRouteChildren {
  BanksSlugPortalAccountsRoute: typeof BanksSlugPortalAccountsRoute
  BanksSlugPortalProfileRoute: typeof BanksSlugPortalProfileRoute
  BanksSlugPortalIndexRoute: typeof BanksSlugPortalIndexRoute
}

const BanksSlugPortalRouteChildren: BanksSlugPortalRouteChildren = {
  BanksSlugPortalAccountsRoute: BanksSlugPortalAccountsRoute,
  BanksSlugPortalProfileRoute: BanksSlugPortalProfileRoute,
  BanksSlugPortalIndexRoute: BanksSlugPortalIndexRoute,
}

const BanksSlugPortalRouteWithChildren = BanksSlugPortalRoute._addFileChildren(
  BanksSlugPortalRouteChildren,
)

interface BanksSlugRouteChildren {
  BanksSlugPageRoute: typeof BanksSlugPageRoute
  BanksSlugForgotRoute: typeof BanksSlugForgotRoute
  BanksSlugLoginRoute: typeof BanksSlugLoginRoute
  BanksSlugPortalRoute: typeof BanksSlugPortalRouteWithChildren
  BanksSlugRegisterRoute: typeof BanksSlugRegisterRoute
}

const BanksSlugRouteChildren: BanksSlugRouteChildren = {
  BanksSlugPageRoute: BanksSlugPageRoute,
  BanksSlugForgotRoute: BanksSlugForgotRoute,
  BanksSlugLoginRoute: BanksSlugLoginRoute,
  BanksSlugPortalRoute: BanksSlugPortalRouteWithChildren,
  BanksSlugRegisterRoute: BanksSlugRegisterRoute,
}

const BanksSlugRouteWithChildren = BanksSlugRoute._addFileChildren(
  BanksSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BankBuilderRoute: BankBuilderRoute,
  LaunchRoute: LaunchRouteWithChildren,
  BanksSlugRoute: BanksSlugRouteWithChildren,
  ManageBanksIdRoute: ManageBanksIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
